project_name: "storage-project"
rhmap_smtp_usernane: "username"
rhmap_smtp_password: "password"
rhmap_smtp_port: "25"
rhmap_smtp_auth: "false"
rhmap_smtp_tls: "false"
rhmap_smtp_replyto: "noreply@localhost"
