- name: Create storage project
  command:  oc new-project {{project_name}}
  tags: gluster-install
- name: Modify scc
  command: oc adm policy add-scc-to-user privileged -z default
  tags: gluster-install
- name: Create topology file
  template:
    src: topology.j2
    dest: "{{topology_file}}"
- name: Deploy Gluster
  command: "cns-deploy -n {{project_name}} -g {{topology_file}}"
  tags: gluster-install
